import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.sx.mapper.LuckSignMapper;
import com.sx.pojo.FamousQuotes;
import com.sx.pojo.LuckSign;
import com.sx.pojo.YiJI;
import com.sx.service.LuckSignService;
import com.sx.until.XinyunqianTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import javax.naming.BinaryRefAddr;
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:applicationContext.xml")
public class StringTest {
  @Autowired
  private LuckSignService luckSignService;
  @Autowired
  private LuckSignMapper luckSignMapper;

    @Test
    public void test1(){
        String aaaa="abcdefgh";
        String bbbb="AbcdEfgH";

        System.out.println(aaaa.equalsIgnoreCase(bbbb));
    }
    @Test
    public void test2(){
        for (int i = 0; i < 4000; i++) {
            XinyunqianTest jt = new XinyunqianTest();
            try {
                String response= jt.httpClient();
                LuckSign luckSign= JSONObject.parseObject(response,LuckSign.class);
                System.out.println(i);
                try{
                luckSignService.addLuckSign(luckSign);
                }catch (Exception e){

                }
                try{
                    luckSignService.addji(luckSign);
                }catch (Exception e){

                }
                try{
                    luckSignService.addyi(luckSign);
                }catch (Exception e){

                }
                try{
                    luckSignService.addLuckSignTwo(luckSign);
                }catch (Exception e){

                }

                FamousQuotes famousQuotes=JSONObject.parseObject(luckSign.getSloganDetail(),FamousQuotes.class);
                luckSignService.addFamousQutos(famousQuotes);
            } catch (Exception e) {

            }
        }

    }
    @Test
    public void test3()throws Exception{
        String yi="{\n" +
                "\"RECORDS\":[\n" +
                "{\n" +
                "\"id\":42,\n" +
                "\"suitable\":\"K歌\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":66,\n" +
                "\"suitable\":\"一丝不苟\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":524,\n" +
                "\"suitable\":\"一心一意\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":210,\n" +
                "\"suitable\":\"一身正气\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":54,\n" +
                "\"suitable\":\"上交国家\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":24,\n" +
                "\"suitable\":\"不动声色\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":163,\n" +
                "\"suitable\":\"不屈不挠\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":119,\n" +
                "\"suitable\":\"不耻下问\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":261,\n" +
                "\"suitable\":\"中二\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":101,\n" +
                "\"suitable\":\"临危不惧\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":155,\n" +
                "\"suitable\":\"争分夺秒\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":333,\n" +
                "\"suitable\":\"井井有条\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":110,\n" +
                "\"suitable\":\"仔细\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":44,\n" +
                "\"suitable\":\"代人受过\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":58,\n" +
                "\"suitable\":\"众筹\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":319,\n" +
                "\"suitable\":\"作保证\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":592,\n" +
                "\"suitable\":\"信奉\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":20,\n" +
                "\"suitable\":\"健身\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":198,\n" +
                "\"suitable\":\"傲娇\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":87,\n" +
                "\"suitable\":\"充实\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":2,\n" +
                "\"suitable\":\"先人后己\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":46,\n" +
                "\"suitable\":\"光明磊落\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":1941,\n" +
                "\"suitable\":\"克己奉公\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":538,\n" +
                "\"suitable\":\"全力以赴\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":468,\n" +
                "\"suitable\":\"全神贯注\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":13,\n" +
                "\"suitable\":\"再接再厉\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":103,\n" +
                "\"suitable\":\"冒险\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":122,\n" +
                "\"suitable\":\"冥想\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":1037,\n" +
                "\"suitable\":\"凝聚\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":21,\n" +
                "\"suitable\":\"出行\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":100,\n" +
                "\"suitable\":\"分享\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":369,\n" +
                "\"suitable\":\"创作\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":235,\n" +
                "\"suitable\":\"别具一格\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":147,\n" +
                "\"suitable\":\"前行\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":61,\n" +
                "\"suitable\":\"力争上游\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":5,\n" +
                "\"suitable\":\"力挽狂澜\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":53,\n" +
                "\"suitable\":\"加班\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":23,\n" +
                "\"suitable\":\"勇敢\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":224,\n" +
                "\"suitable\":\"勤劳\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":89,\n" +
                "\"suitable\":\"卷土重来\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":51,\n" +
                "\"suitable\":\"厉害word哥\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":251,\n" +
                "\"suitable\":\"厚道\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":157,\n" +
                "\"suitable\":\"反败为胜\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":71,\n" +
                "\"suitable\":\"发呆\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":553,\n" +
                "\"suitable\":\"发朋友圈\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":94,\n" +
                "\"suitable\":\"变身\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":72,\n" +
                "\"suitable\":\"叙旧\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":379,\n" +
                "\"suitable\":\"吃土\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":489,\n" +
                "\"suitable\":\"吃炸鸡\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":460,\n" +
                "\"suitable\":\"吃瓜看戏\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":394,\n" +
                "\"suitable\":\"听从\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":254,\n" +
                "\"suitable\":\"呵呵\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":6,\n" +
                "\"suitable\":\"回忆\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":39,\n" +
                "\"suitable\":\"团结\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":200,\n" +
                "\"suitable\":\"坚定不移\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":302,\n" +
                "\"suitable\":\"坚强\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":9,\n" +
                "\"suitable\":\"坚强不屈\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":131,\n" +
                "\"suitable\":\"堂堂正正\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":250,\n" +
                "\"suitable\":\"壁咚\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":7,\n" +
                "\"suitable\":\"处CP\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":52,\n" +
                "\"suitable\":\"夜跑\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":240,\n" +
                "\"suitable\":\"大方\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":97,\n" +
                "\"suitable\":\"天真烂漫\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":84,\n" +
                "\"suitable\":\"失眠\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":288,\n" +
                "\"suitable\":\"好奇\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":397,\n" +
                "\"suitable\":\"妖艳\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":3,\n" +
                "\"suitable\":\"委婉\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":10,\n" +
                "\"suitable\":\"威武不屈\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":27,\n" +
                "\"suitable\":\"孜孜不倦\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":88,\n" +
                "\"suitable\":\"定小目标\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":168,\n" +
                "\"suitable\":\"定投\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":45,\n" +
                "\"suitable\":\"客观\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":98,\n" +
                "\"suitable\":\"容光焕发\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":386,\n" +
                "\"suitable\":\"宽容\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":67,\n" +
                "\"suitable\":\"对牛弹琴\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":125,\n" +
                "\"suitable\":\"小憩\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":222,\n" +
                "\"suitable\":\"小确幸\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":177,\n" +
                "\"suitable\":\"就坡下驴\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":136,\n" +
                "\"suitable\":\"干干脆脆\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":165,\n" +
                "\"suitable\":\"平凡\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":875,\n" +
                "\"suitable\":\"平淡\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":1092,\n" +
                "\"suitable\":\"平静\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":344,\n" +
                "\"suitable\":\"幻想\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":185,\n" +
                "\"suitable\":\"废寝忘食\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":159,\n" +
                "\"suitable\":\"建仓\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":38,\n" +
                "\"suitable\":\"开仓\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":49,\n" +
                "\"suitable\":\"开心就好\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":12,\n" +
                "\"suitable\":\"开黑\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":59,\n" +
                "\"suitable\":\"当宝宝 \"\n" +
                "},\n" +
                "{\n" +
                "\"id\":86,\n" +
                "\"suitable\":\"当机立断\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":15,\n" +
                "\"suitable\":\"当老司机\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":149,\n" +
                "\"suitable\":\"徘徊\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":91,\n" +
                "\"suitable\":\"微笑\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":622,\n" +
                "\"suitable\":\"心平气和\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":263,\n" +
                "\"suitable\":\"忠贞不渝\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":232,\n" +
                "\"suitable\":\"思念\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":74,\n" +
                "\"suitable\":\"恋爱\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":167,\n" +
                "\"suitable\":\"想静静\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":36,\n" +
                "\"suitable\":\"慎言谨行\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":154,\n" +
                "\"suitable\":\"慎重\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":82,\n" +
                "\"suitable\":\"憨厚\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":252,\n" +
                "\"suitable\":\"成人之美\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":113,\n" +
                "\"suitable\":\"打白条\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":55,\n" +
                "\"suitable\":\"打赌\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":73,\n" +
                "\"suitable\":\"抖腿\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":203,\n" +
                "\"suitable\":\"披荆斩棘\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":320,\n" +
                "\"suitable\":\"押话题\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":1,\n" +
                "\"suitable\":\"抽奖\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":178,\n" +
                "\"suitable\":\"担当\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":18,\n" +
                "\"suitable\":\"拍照\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":135,\n" +
                "\"suitable\":\"拍胸脯\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":56,\n" +
                "\"suitable\":\"拍马屁\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":29,\n" +
                "\"suitable\":\"拘谨\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":704,\n" +
                "\"suitable\":\"挽尊\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":281,\n" +
                "\"suitable\":\"捏方便面\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":284,\n" +
                "\"suitable\":\"推心置腹\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":218,\n" +
                "\"suitable\":\"撩\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":421,\n" +
                "\"suitable\":\"撩妹\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":487,\n" +
                "\"suitable\":\"放空\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":50,\n" +
                "\"suitable\":\"敬重\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":311,\n" +
                "\"suitable\":\"断舍离\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":4,\n" +
                "\"suitable\":\"新欢\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":144,\n" +
                "\"suitable\":\"歌唱\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":41,\n" +
                "\"suitable\":\"沉淀\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":219,\n" +
                "\"suitable\":\"洪荒之力\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":30,\n" +
                "\"suitable\":\"活泼\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":212,\n" +
                "\"suitable\":\"流汗\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":145,\n" +
                "\"suitable\":\"流浪\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":70,\n" +
                "\"suitable\":\"浅尝辄止\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":293,\n" +
                "\"suitable\":\"涨姿势\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":166,\n" +
                "\"suitable\":\"添衣\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":62,\n" +
                "\"suitable\":\"温暖\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":260,\n" +
                "\"suitable\":\"熬夜\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":826,\n" +
                "\"suitable\":\"理财\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":173,\n" +
                "\"suitable\":\"甜言蜜语\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":686,\n" +
                "\"suitable\":\"画龙点睛\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":60,\n" +
                "\"suitable\":\"疏离\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":372,\n" +
                "\"suitable\":\"痛快\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":142,\n" +
                "\"suitable\":\"百折不挠\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":526,\n" +
                "\"suitable\":\"直白\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":26,\n" +
                "\"suitable\":\"直言不讳\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":196,\n" +
                "\"suitable\":\"看电影\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":64,\n" +
                "\"suitable\":\"真心诚意\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":77,\n" +
                "\"suitable\":\"破釜沉舟\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":385,\n" +
                "\"suitable\":\"称霸一方\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":208,\n" +
                "\"suitable\":\"简单\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":459,\n" +
                "\"suitable\":\"精力充沛\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":93,\n" +
                "\"suitable\":\"精致\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":76,\n" +
                "\"suitable\":\"精雕细刻\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":161,\n" +
                "\"suitable\":\"糊涂\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":11,\n" +
                "\"suitable\":\"练字\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":639,\n" +
                "\"suitable\":\"群策群力\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":40,\n" +
                "\"suitable\":\"老成持重\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":657,\n" +
                "\"suitable\":\"聚会\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":374,\n" +
                "\"suitable\":\"肝胆相照\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":141,\n" +
                "\"suitable\":\"脑补\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":213,\n" +
                "\"suitable\":\"自恋\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":216,\n" +
                "\"suitable\":\"自惭形秽\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":282,\n" +
                "\"suitable\":\"自我迭代\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":108,\n" +
                "\"suitable\":\"自知\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":418,\n" +
                "\"suitable\":\"舍己为人\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":128,\n" +
                "\"suitable\":\"舒畅\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":22,\n" +
                "\"suitable\":\"虚怀若谷\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":8,\n" +
                "\"suitable\":\"表白\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":117,\n" +
                "\"suitable\":\"装傻\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":190,\n" +
                "\"suitable\":\"誓死不二\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":308,\n" +
                "\"suitable\":\"订餐\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":162,\n" +
                "\"suitable\":\"诚实\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":16,\n" +
                "\"suitable\":\"说三遍\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":217,\n" +
                "\"suitable\":\"赖床\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":758,\n" +
                "\"suitable\":\"赞许\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":32,\n" +
                "\"suitable\":\"赤胆忠心\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":14,\n" +
                "\"suitable\":\"起来嗨\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":69,\n" +
                "\"suitable\":\"超脱\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":80,\n" +
                "\"suitable\":\"跑江湖\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":375,\n" +
                "\"suitable\":\"路过\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":106,\n" +
                "\"suitable\":\"蹲点\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":112,\n" +
                "\"suitable\":\"转发锦鲤\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":31,\n" +
                "\"suitable\":\"迂回\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":244,\n" +
                "\"suitable\":\"还白条\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":241,\n" +
                "\"suitable\":\"远方\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":19,\n" +
                "\"suitable\":\"追随\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":48,\n" +
                "\"suitable\":\"逃离\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":285,\n" +
                "\"suitable\":\"遗忘\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":47,\n" +
                "\"suitable\":\"遵循\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":105,\n" +
                "\"suitable\":\"邂逅\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":114,\n" +
                "\"suitable\":\"长个\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":140,\n" +
                "\"suitable\":\"长久\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":37,\n" +
                "\"suitable\":\"闪付\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":34,\n" +
                "\"suitable\":\"闲谈\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":237,\n" +
                "\"suitable\":\"闻鸡起舞\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":305,\n" +
                "\"suitable\":\"阅读\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":362,\n" +
                "\"suitable\":\"集思广益\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":156,\n" +
                "\"suitable\":\"雪中送炭\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":220,\n" +
                "\"suitable\":\"静静\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":227,\n" +
                "\"suitable\":\"面试\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":171,\n" +
                "\"suitable\":\"鞠躬尽瘁\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":479,\n" +
                "\"suitable\":\"领福利\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":96,\n" +
                "\"suitable\":\"饱食终日\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":351,\n" +
                "\"suitable\":\"鲜艳\"\n" +
                "},\n" +
                "{\n" +
                "\"id\":63,\n" +
                "\"suitable\":\"鹤立鸡群\"\n" +
                "}\n" +
                "]\n" +
                "}";
        String ji="{\n" +
                "\"RECORDS\":[\n" +
                "{\n" +
                "\"avoid\":\"一毛不拔\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"上天\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"不分皂白\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"不可描述\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"严厉\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"为虎作伥\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"乏味\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"乐不思蜀\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"互怼\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"互相伤害\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"任性\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"伤不起\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"伪装\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"作梗\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"倔强\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"内心崩溃\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"冒进\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"冷冷清清\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"别扭\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"剁手\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"力倦神疲\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"匆匆\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"卖萌\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"压抑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"反对\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"反悔\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"口出不逊\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"口是心非\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"口若悬河\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"名不副实\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"吐槽\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"吓人\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"吝啬\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"吞吞吐吐\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"否认\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"含糊\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"呆板\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"喧闹\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"嘚瑟\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"围观\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"坑爹\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"复杂\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"大材小用\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"大笑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"大言不惭\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"太美不敢看\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"失信\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"夸夸其谈\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"套路\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"好为人师\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"妄自尊大\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"嫑骗人\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"孤单\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"孤芳自赏\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"孤陋寡闻\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"宅\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"完美主义\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"定目标\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"对牛谈情\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"将薪比薪\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"居功自傲\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"平仓\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"张牙舞爪\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"强说忧愁\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"彷徨\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"心不在焉\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"心塞\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"心好累\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"忘乎所以\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"忧虑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"怀疑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"怒放\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"思前想后\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"悲观\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"惊慌失措\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"惟我独尊\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"惹是生非\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"慌张\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"懒惰\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"我好方\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"手滑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"扎心\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"打酱油\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"执迷不悟\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"抵赖\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"拐弯抹角\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"拒绝\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"招猫递狗\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"掏空身体\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"摆谱儿\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"撒谎\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"撕B\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"故弄玄虚\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"敲边鼓\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"无力回天\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"无言以对\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"暗淡\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"暧昧\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"暴食\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"有钱任性\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"杂乱\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"污\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"浑浊\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"浮夸\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"清纯不做作\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"激烈\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"火气\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"灰心丧气\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"炫富\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"点赞\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"烦忧\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"爬起来哭\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"猜疑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"班门弄斧\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"画蛇添足\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"目中无人\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"目瞪口呆\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"目空一切\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"盲人摸象\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"看国足\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"眼高手低\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"空谈\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"等待\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"粗心\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"粗暴\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"纠结\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"翻来覆去\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"肆无忌惮\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"胆怯\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"背弃\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"脸着地\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"脸红筋暴\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"自命不凡\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"自恋\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"自暴自弃\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"自高自大\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"自鸣得意\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"花言巧语\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"苟且\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"落井下石\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"蓝瘦香菇\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"薄弱\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"虚情假意\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"袖手傍观\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"见礼忘义\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"见风使舵\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"语无伦次\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"调皮\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"贪杯\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"走神\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"趁火打劫\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"软弱\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"轻信\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"轻蔑\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"辣眼睛\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"过河拆桥\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"违背\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"退让\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"逗比\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"逗留\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"酸奶舔盖\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"重复\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"闪转腾挪\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"闲言碎语\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"随便\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"隔岸观火\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"颓靡\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"飙车\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"鹬蚌相争\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"黔驴技穷\"\n" +
                "},\n" +
                "{\n" +
                "\"avoid\":\"鼠目寸光\"\n" +
                "}\n" +
                "]\n" +
                "}";

        JSONObject jsonObject=JSONObject.parseObject(yi);
        JSONArray yiArray=jsonObject.getJSONArray("RECORDS");
        JSONObject jsonObject1=JSONObject.parseObject(ji);
        JSONArray jiArray=jsonObject1.getJSONArray("RECORDS");
        int a=1;
        for (int i = 0; i < yiArray.size(); i++) {
            JSONObject jsonObject2=yiArray.getJSONObject(i);
            String yiStr=jsonObject2.getString("suitable");
            for (int j = 0; j < jiArray.size(); j++) {
                JSONObject jsonObject3=jiArray.getJSONObject(j);
                String jiStr=jsonObject3.getString("avoid");
                YiJI yiJI=new YiJI();
                yiJI.setAvoid(jiStr);
                yiJI.setSuitable(yiStr);
                yiJI.setStatus("1");
                luckSignService.addFinalLuckSign(yiJI);
                a++;
                Thread.sleep(30);
                System.out.println(a);
            }
        }
    }
}
